# Generated by Django 4.1.2 on 2022-10-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conhecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Serviços')),
                ('descricao1', models.TextField(default='', max_length=250, verbose_name='Descrição 1')),
                ('descricao2', models.TextField(default='', max_length=250, verbose_name='Descrição 2')),
                ('video', models.FileField(upload_to='videos', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='SegundaParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Quem Somos')),
                ('image1', models.ImageField(upload_to='fotos', verbose_name='Imagem 1')),
                ('descricao1', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 1')),
                ('image2', models.ImageField(upload_to='fotos', verbose_name='Imagem 2')),
                ('descricao2', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 2')),
                ('image3', models.ImageField(upload_to='fotos', verbose_name='Imagem 3')),
                ('descricao3', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 3')),
                ('image4', models.ImageField(upload_to='fotos', verbose_name='Imagem 4')),
                ('descricao4', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 4')),
                ('image5', models.ImageField(upload_to='fotos', verbose_name='Imagem 5')),
                ('descricao5', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 5')),
                ('image6', models.ImageField(upload_to='fotos', verbose_name='Imagem 6')),
                ('descricao6', models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 6')),
            ],
        ),
        migrations.DeleteModel(
            name='QuemSomos',
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='text_button',
        ),
        migrations.AddField(
            model_name='inicio',
            name='text_button1',
            field=models.CharField(default='', max_length=100, verbose_name='Texto-Botão 1'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='text_button2',
            field=models.CharField(default='', max_length=100, verbose_name='Texto-Botão 2'),
        ),
    ]
