# Generated by Django 4.1.2 on 2022-10-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0002_conhecer_segundaparte_delete_quemsomos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='descricao2',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='titulo2',
        ),
    ]
