# Generated by Django 4.1.2 on 2022-10-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0003_remove_inicio_descricao2_remove_inicio_titulo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaparte',
            name='tituloprincipal',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo principal'),
        ),
    ]
