# Generated by Django 4.1.2 on 2022-10-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0004_segundaparte_tituloprincipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segundaparte',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='segundaparte',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='segundaparte',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='segundaparte',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='segundaparte',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='segundaparte',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='segundaparte',
            name='titulo',
        ),
        migrations.AddField(
            model_name='segundaparte',
            name='titulo1',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo 1'),
        ),
        migrations.AddField(
            model_name='segundaparte',
            name='titulo2',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo 2'),
        ),
        migrations.AddField(
            model_name='segundaparte',
            name='titulo3',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo 3'),
        ),
        migrations.AddField(
            model_name='segundaparte',
            name='titulo4',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo 4'),
        ),
        migrations.AddField(
            model_name='segundaparte',
            name='titulo5',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo 5'),
        ),
        migrations.AddField(
            model_name='segundaparte',
            name='titulo6',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo 6'),
        ),
    ]
