# Generated by Django 4.1.2 on 2022-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0005_remove_segundaparte_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conhecer',
            name='descricao1',
        ),
        migrations.RemoveField(
            model_name='conhecer',
            name='descricao2',
        ),
        migrations.AddField(
            model_name='conhecer',
            name='descricao',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição'),
        ),
    ]
