# Generated by Django 4.1.2 on 2022-10-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0006_remove_conhecer_descricao1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='autor1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='autor2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='autor3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='autor4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='comentario1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='comentario2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='comentario3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='comentario4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image6',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='descricao',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='text_button',
            field=models.CharField(default='', max_length=100, verbose_name='Texto-Botão'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='titulo',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo'),
        ),
    ]
