# Generated by Django 4.1.2 on 2022-10-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0007_remove_portfolio_autor1_remove_portfolio_autor2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
    ]
