# Generated by Django 4.1.2 on 2022-10-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio2', '0009_alter_conhecer_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
